export const PRIZES_LIST_REQUEST = "PRIZES_LIST_REQUEST";
export const PRIZES_LIST_SUCCESS = "PRIZES_LIST_SUCCESS";
export const PRIZES_LIST_FAIL = "PRIZES_LIST_FAIL";

export const PRIZES_CREATE_REQUEST = "PRIZES_CREATE_REQUEST";
export const PRIZES_CREATE_SUCCESS = "PRIZES_CREATE_SUCCESS";
export const PRIZES_CREATE_FAIL = "PRIZES_CREATE_FAIL";

export const PRIZES_DELETE_REQUEST = "PRIZES_DELETE_REQUEST";
export const PRIZES_DELETE_SUCCESS = "PRIZES_DELETE_SUCCESS";
export const PRIZES_DELETE_FAIL = "PRIZES_DELETE_FAIL";
